export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_CONFIGURATION_SUCCESS = 'LOAD_CONFIGURATION_SUCCESS';
export const LOAD_EMAIL_CONFIGURATION_SUCCESS = 'LOAD_EMAIL_CONFIGURATION_SUCCESS';
export const UPDATE_EMAILCONFIG_SUCCESS = 'UPDATE_EMAILCONFIG_SUCCESS';
export const UPDATE_EMAILCONFIG_ERROR = 'UPDATE_EMAILCONFIG_ERROR';
export const LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_ERROR = 'UPDATE_SETTINGS_ERROR';
